from django.core.management.base import BaseCommand

from documents.models import Authority
from submissions.models import DocumentRoute

ROUTES = [
    {
        "route_id": "T01",
        "name": "Проект ГРР / Экспертиза ГРР",
        "document_process": "Проект ГРР; Экспертиза ГРР",
        "authority_name": "ФГКУ Росгеолэкспертиза",
        "template_name": "Заявка на проведение экспертизы проектной документации ГРР",
        "required_fields": [
            "company_full_name",
            "inn",
            "license_number",
            "object_name",
            "project_name",
            "contact_person",
        ],
        "required_attachments": [
            "project_documentation",
            "calendar_plan",
            "license_file",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.MANUAL,
        "source_url": "https://www.rgexp.ru/",
        "note": "Сервис должен различать полную экспертизу и экспертизу календарного плана.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T02",
        "name": "Протокол ТКЗ / ТЭО кондиций / материалы запасов",
        "document_process": "Протокол ТКЗ; ТЭО кондиций; материалы запасов",
        "authority_name": "ФБУ ГКЗ / ТКЗ по компетенции",
        "template_name": "Заявление на проведение государственной экспертизы запасов",
        "required_fields": [
            "company_full_name",
            "inn",
            "license_number",
            "object_name",
            "mineral_type",
            "requested_action",
            "contact_person",
        ],
        "required_attachments": [
            "reserves_calculation_materials",
            "feasibility_study",
            "license_file",
            "power_of_attorney",
            "cover_letter",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.MANUAL,
        "source_url": "https://gkz-rf.ru/",
        "note": "По ОПИ/местному значению проверить, не относится ли участок к компетенции субъекта.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T03",
        "name": "Технический проект / Протокол ТКР",
        "document_process": "Технический проект; изменение календарного плана; протокол ТКР",
        "authority_name": "Уралнедра",
        "template_name": "Заявление о согласовании технического проекта / изменений",
        "required_fields": [
            "company_full_name",
            "inn",
            "license_number",
            "object_name",
            "project_name",
            "requested_action",
            "contact_person",
        ],
        "required_attachments": [
            "technical_project",
            "license_file",
            "reserves_protocol",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.AGENCY_ACCOUNT,
        "source_url": "https://rosnedra.gov.ru/",
        "note": "E-mail не должен быть единственным каналом подачи.",
        "risk_level": DocumentRoute.RiskLevel.HIGH,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T04",
        "name": "Горный отвод",
        "document_process": "Горный отвод",
        "authority_name": "Уральское управление Ростехнадзора",
        "template_name": "Заявление об оформлении/уточнении документов горного отвода",
        "required_fields": [
            "company_full_name",
            "inn",
            "license_number",
            "object_name",
            "mineral_type",
            "contact_person",
        ],
        "required_attachments": [
            "license_file",
            "approved_technical_project",
            "mining_allotment_coordinates",
            "tkr_protocol",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.OFFICE,
        "source_url": "https://www.ural.gosnadzor.ru/contacts/",
        "note": "Нужен контроль связки: техпроект согласован -> горный отвод -> ПРГР.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T05",
        "name": "Проект ликвидации объекта",
        "document_process": "Проект ликвидации объекта",
        "authority_name": "Уралнедра / Роснедра",
        "template_name": "Заявление о согласовании технического проекта ликвидации/консервации",
        "required_fields": [
            "company_full_name",
            "inn",
            "license_number",
            "object_name",
            "project_name",
            "requested_action",
            "contact_person",
        ],
        "required_attachments": [
            "liquidation_project",
            "calculations",
            "reclamation_solutions",
            "ecological_opinion",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.AGENCY_ACCOUNT,
        "source_url": "https://ufo.rosnedra.gov.ru/stranitsy/kontakty/",
        "note": "Учитывать сроки лицензии и рекультивации.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T06",
        "name": "Лицензия: продление, изменение, переоформление",
        "document_process": "Лицензия: продление; изменение; переоформление",
        "authority_name": "Роснедра / Уралнедра",
        "template_name": "Заявление о внесении изменений/переоформлении/продлении лицензии",
        "required_fields": [
            "company_full_name",
            "inn",
            "license_number",
            "license_end_date",
            "object_name",
            "requested_action",
            "contact_person",
        ],
        "required_attachments": [
            "license_file",
            "license_conditions_confirmation",
            "technical_project_or_protocols",
            "power_of_attorney",
            "state_duty_receipt",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.AGENCY_ACCOUNT,
        "source_url": "https://rosnedra.gov.ru/activity/gosudarstvennye-uslugi/litsenzirovanie-polzovaniya-nedrami/",
        "note": "Хранить дату окончания каждой лицензии как отдельное обязательное поле.",
        "risk_level": DocumentRoute.RiskLevel.HIGH,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T07",
        "name": "ПРГР",
        "document_process": "ПРГР; ПРГР 2025; ПРГР 2026",
        "authority_name": "Уральское управление Ростехнадзора",
        "template_name": "Заявление о согласовании плана и/или схемы развития горных работ",
        "required_fields": [
            "company_full_name",
            "inn",
            "license_number",
            "object_name",
            "mineral_type",
            "contact_person",
        ],
        "required_attachments": [
            "mine_development_plan",
            "explanatory_note",
            "graphic_part",
            "technical_project",
            "mining_allotment",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "https://www.ural.gosnadzor.ru/activity/plans/",
        "note": "Приказ №537 действует до 01.01.2027; в 2027 проверить новый порядок.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T08",
        "name": "Лицензия на маркшейдерские работы",
        "document_process": "Лицензия на ведение маркшейдерских работ",
        "authority_name": "Ростехнадзор",
        "template_name": "Заявление о предоставлении/переоформлении лицензии на маркшейдерские работы",
        "required_fields": [
            "company_full_name",
            "inn",
            "ogrn",
            "contact_person",
        ],
        "required_attachments": [
            "founding_documents",
            "staff_qualification_docs",
            "equipment_documents",
            "power_of_attorney",
            "state_duty_receipt",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "https://www.ural.gosnadzor.ru/contacts/",
        "note": "Если работы выполняет подрядчик — хранить его лицензию и срок действия.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T09",
        "name": "План лесного участка / кадастровые работы",
        "document_process": "План лесного участка; проект на земли; кадастровые работы в лесном фонде",
        "authority_name": "Минприроды Свердловской области",
        "template_name": "Заявление о формировании лесного участка / предоставлении данных / согласовании кадастровых работ",
        "required_fields": [
            "company_full_name",
            "inn",
            "license_number",
            "object_name",
            "forest_district",
            "contact_person",
        ],
        "required_attachments": [
            "layout_scheme",
            "coordinates",
            "license_file",
            "site_plan",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "https://mprso.midural.ru/activity/566/",
        "note": "Критичные поля: лесничество, участковое лесничество, квартал, выдел.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T10",
        "name": "Договор аренды лесного участка",
        "document_process": "Договор аренды лесного участка",
        "authority_name": "Минприроды Свердловской области",
        "template_name": "Заявление о предоставлении лесного участка в аренду",
        "required_fields": [
            "company_full_name",
            "inn",
            "license_number",
            "forest_district",
            "land_holder",
            "contact_person",
        ],
        "required_attachments": [
            "plot_scheme",
            "cadastral_materials",
            "license_file",
            "applicant_documents",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "https://mprso.midural.ru/activity/566/",
        "note": "Напоминать о продлении/новом договоре заранее.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T11",
        "name": "Проект освоения лесов / экспертиза проекта",
        "document_process": "Проект освоения лесов; экспертиза проекта",
        "authority_name": "Минприроды Свердловской области",
        "template_name": "Заявление о проведении государственной экспертизы проекта освоения лесов",
        "required_fields": [
            "company_full_name",
            "inn",
            "forest_district",
            "contact_person",
        ],
        "required_attachments": [
            "forest_development_project",
            "lease_agreement",
            "plot_plan",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "https://mprso.midural.ru/activity/566/",
        "note": "Блокировать лесную декларацию без положительной экспертизы ПОЛ.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T12",
        "name": "Лесная декларация",
        "document_process": "Лесная декларация",
        "authority_name": "Минприроды Свердловской области",
        "template_name": "Лесная декларация по утвержденной форме",
        "required_fields": [
            "company_full_name",
            "forest_district",
            "contact_person",
        ],
        "required_attachments": [
            "forest_declaration",
            "forest_development_expertise",
            "lease_agreement",
            "site_map",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "https://mprso.midural.ru/activity/566/",
        "note": "Связка с календарем работ — декларация до начала периода лесопользования.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T13",
        "name": "Лесовосстановление",
        "document_process": "Лесовосстановление",
        "authority_name": "Минприроды Свердловской области",
        "template_name": "Уведомление/проект/отчет о лесовосстановлении",
        "required_fields": [
            "company_full_name",
            "forest_district",
            "contact_person",
        ],
        "required_attachments": [
            "reforestation_project_or_report",
            "plot_map",
            "agreement",
            "photo_confirmation",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.OFFICE,
        "source_url": "https://mprso.midural.ru/activity/566/",
        "note": "Форму привязать к виду обязанности: компенсационное/искусственное/комбинированное.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T14",
        "name": "Рекультивация / проект рекультивации",
        "document_process": "Рекультивация; проект рекультивации",
        "authority_name": "Орган по категории/правообладателю земли (уточняется)",
        "template_name": "Проект рекультивации / сопроводительное письмо о согласовании / письмо о сдаче работ",
        "required_fields": [
            "company_full_name",
            "land_cadastral_number",
            "land_category",
            "land_holder",
            "deadline_external",
            "court_case_ref",
            "contact_person",
        ],
        "required_attachments": [
            "reclamation_project",
            "cost_estimate",
            "ownership_documents",
            "agreements",
            "acts",
            "photo_confirmation",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.MANUAL,
        "source_url": "http://government.ru/docs/33190/",
        "note": "Хранить два дедлайна: срок завершения работ и срок сдачи/акта приемки.",
        "risk_level": DocumentRoute.RiskLevel.HIGH,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T15",
        "name": "Межевой план",
        "document_process": "Межевой план",
        "authority_name": "Росреестр / МФЦ / КУМИ по маршруту участка",
        "template_name": "Заявление о кадастровом учете / передача межевого плана",
        "required_fields": [
            "company_full_name",
            "land_cadastral_number",
            "municipality",
            "contact_person",
        ],
        "required_attachments": [
            "land_survey_plan",
            "layout_scheme",
            "ownership_documents",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "",
        "note": "Лучше вести как вложение к земельному маршруту, а не отдельное письмо.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T16",
        "name": "Перевод категории ЗУ",
        "document_process": "Перевод категории ЗУ",
        "authority_name": "Рослесхоз",
        "template_name": "Ходатайство о переводе земельного участка из одной категории в другую",
        "required_fields": [
            "company_full_name",
            "land_cadastral_number",
            "land_category",
            "forest_district",
            "contact_person",
        ],
        "required_attachments": [
            "ownership_documents",
            "cadastral_data",
            "layout_scheme",
            "subsoil_license",
            "justification",
            "consents",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "https://rosleshoz.gov.ru/",
        "note": "Сначала определить исходную категорию земли.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T17",
        "name": "Изменение разрешенного использования ЗУ",
        "document_process": "Изменение разрешенного использования ЗУ",
        "authority_name": "Администрация / КУМИ / Росреестр по месту участка",
        "template_name": "Заявление об изменении вида разрешенного использования",
        "required_fields": [
            "company_full_name",
            "land_cadastral_number",
            "municipality",
            "contact_person",
        ],
        "required_attachments": [
            "egrn_extract",
            "layout_scheme",
            "plot_documents",
            "license_file",
            "justification",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "",
        "note": "Автоматизация невозможна без кадастрового номера и ПЗЗ.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T18",
        "name": "Договор аренды ЗУ",
        "document_process": "Договор аренды ЗУ",
        "authority_name": "КУМИ / администрация",
        "template_name": "Заявление о предоставлении земельного участка в аренду",
        "required_fields": [
            "company_full_name",
            "land_cadastral_number",
            "municipality",
            "land_holder",
            "contact_person",
        ],
        "required_attachments": [
            "plot_scheme_or_survey",
            "egrn_extract",
            "license_file",
            "vri_or_transfer_decision",
            "draft_agreement",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.OFFICE,
        "source_url": "",
        "note": "Адресат должен определяться по owner_type и municipality.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T19",
        "name": "Постановление администрации НГО/НТГО",
        "document_process": "Постановление администрации НГО/НТГО",
        "authority_name": "Администрация соответствующего городского округа",
        "template_name": "Заявление о принятии муниципального правового акта",
        "required_fields": [
            "company_full_name",
            "municipality",
            "requested_action",
            "contact_person",
        ],
        "required_attachments": [
            "land_documents_package",
            "approvals",
            "license_file",
            "layout_scheme",
            "draft_resolution",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.OFFICE,
        "source_url": "",
        "note": "Нужно расшифровать НГО и НТГО для каждого объекта.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T20",
        "name": "ОЗУ: перевод земель лесного фонда",
        "document_process": "ОЗУ: пакет Рослесхоз / Роснедра / Минприроды РФ / Правительство РФ",
        "authority_name": "Рослесхоз",
        "template_name": "Комплект ходатайства и межведомственных писем по переводу земель лесного фонда",
        "required_fields": [
            "company_full_name",
            "license_number",
            "land_cadastral_number",
            "forest_district",
            "requested_action",
            "contact_person",
        ],
        "required_attachments": [
            "cadastral_data",
            "forestry_materials",
            "layout_scheme",
            "license_file",
            "project_materials",
            "owner_consent",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "https://rosleshoz.gov.ru/",
        "note": "Запускать до земельного этапа с большим запасом; межведомственный маршрут.",
        "risk_level": DocumentRoute.RiskLevel.HIGH,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T21",
        "name": "ПДВ / НДВ / разрешение на выбросы",
        "document_process": "Разработка проекта нормативов ПДВ; нормирование ПДВ/НДВ; разрешение на выбросы",
        "authority_name": "Росприроднадзор",
        "template_name": "Заявление об установлении НДВ/ВРВ/выдаче разрешения на выбросы или декларация/КЭР",
        "required_fields": [
            "company_full_name",
            "nvos_category",
            "object_name",
            "sez_details",
            "contact_person",
        ],
        "required_attachments": [
            "emissions_inventory",
            "ndv_calculations",
            "action_plan_draft",
            "sez_details_file",
            "nvos_data",
            "state_duty_receipt",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.AGENCY_ACCOUNT,
        "source_url": "https://rpn.gov.ru/regions/66/",
        "note": "Сначала спросить категорию НВОС: I, II, III, IV.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T22",
        "name": "СЭЗ на проект",
        "document_process": "Санитарно-эпидемиологическая экспертиза и заключение на проект",
        "authority_name": "Роспотребнадзор по Свердловской области",
        "template_name": "Заявление о выдаче санитарно-эпидемиологического заключения на проектную документацию",
        "required_fields": [
            "company_full_name",
            "project_name",
            "object_name",
            "contact_person",
        ],
        "required_attachments": [
            "project_documentation",
            "sanitary_expertise_results",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "https://www.rospotrebnadzor.ru/",
        "note": "Разделить в сервисе «экспертизу» и «заключение» — это разные стадии.",
        "risk_level": DocumentRoute.RiskLevel.MEDIUM,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T23",
        "name": "Договор водопользования",
        "document_process": "Договор водопользования",
        "authority_name": "Росводресурсы",
        "template_name": "Заявление о предоставлении водного объекта в пользование",
        "required_fields": [
            "company_full_name",
            "water_body_name",
            "water_body_coordinates",
            "deadline_external",
            "contact_person",
        ],
        "required_attachments": [
            "water_body_scheme",
            "coordinates",
            "volume_calculation",
            "land_documents",
            "project_materials",
            "power_of_attorney",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.GOSUSLUGI,
        "source_url": "https://voda.gov.ru/",
        "note": "Действующие договоры продлевать/переоформлять заранее, минимум 90/60/30 дней.",
        "risk_level": DocumentRoute.RiskLevel.HIGH,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T24",
        "name": "Оценка воздействия на ВБР",
        "document_process": "Оценка воздействия на биоресурсы и среду их обитания",
        "authority_name": "Нижнеобское ТУ Росрыболовства",
        "template_name": "Раздел/материалы оценки воздействия на ВБР + сопроводительное письмо",
        "required_fields": [
            "company_full_name",
            "water_body_name",
            "water_body_coordinates",
            "contact_person",
        ],
        "required_attachments": [
            "project_documentation_or_program",
            "impact_assessment",
            "biores_protection_measures",
            "maps",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.POST,
        "source_url": "https://tmn.fish.gov.ru/",
        "note": "Хранить water_body_id и периоды работ в русле/водоохранной зоне.",
        "risk_level": DocumentRoute.RiskLevel.HIGH,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T25",
        "name": "Согласование ХД на водотоке",
        "document_process": "Согласование ведения хозяйственной деятельности на водотоке с ТО Росрыболовства",
        "authority_name": "Нижнеобское ТУ Росрыболовства",
        "template_name": "Заявка о согласовании деятельности, оказывающей воздействие на ВБР и среду их обитания",
        "required_fields": [
            "company_full_name",
            "water_body_name",
            "water_body_coordinates",
            "contact_person",
        ],
        "required_attachments": [
            "project_documentation_or_program",
            "biores_protection_measures",
            "maps_coordinates",
        ],
        "submission_channel": DocumentRoute.SubmissionChannel.POST,
        "source_url": "https://tmn.fish.gov.ru/",
        "note": "Проверять наличие оценки ВБР (T24) до формирования заявки.",
        "risk_level": DocumentRoute.RiskLevel.HIGH,
        "allow_auto_generation": True,
    },
    {
        "route_id": "T26",
        "name": "ГО и ЧС — требуется уточнение",
        "document_process": "ГО и ЧС: документ не расшифрован в файле",
        "authority_name": "МЧС / муниципалитет (уточняется)",
        "template_name": "",
        "required_fields": [
            "object_name",
            "contact_person",
        ],
        "required_attachments": [],
        "submission_channel": DocumentRoute.SubmissionChannel.MANUAL,
        "source_url": "",
        "note": "Не отправлять автоматически без юридической классификации документа.",
        "risk_level": DocumentRoute.RiskLevel.HIGH,
        "allow_auto_generation": False,
    },
    {
        "route_id": "T27",
        "name": "ОПР — требуется уточнение",
        "document_process": "ОПР — в файле не расшифровано",
        "authority_name": "Требуется уточнение",
        "template_name": "",
        "required_fields": [
            "object_name",
            "contact_person",
            "requested_action",
        ],
        "required_attachments": [],
        "submission_channel": DocumentRoute.SubmissionChannel.MANUAL,
        "source_url": "",
        "note": "Не автоматизировать до расшифровки аббревиатуры.",
        "risk_level": DocumentRoute.RiskLevel.HIGH,
        "allow_auto_generation": False,
    },
]


class Command(BaseCommand):
    help = "Create or update document automation routes."

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for raw_route_data in ROUTES:
            route_data = raw_route_data.copy()

            route_id = route_data.pop("route_id")
            authority_name = route_data.pop("authority_name")

            authority, _ = Authority.objects.get_or_create(
                name=authority_name,
            )

            route, created = DocumentRoute.objects.update_or_create(
                route_id=route_id,
                defaults={
                    **route_data,
                    "authority": authority,
                },
            )

            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Routes seeded. Created: {created_count}. Updated: {updated_count}."
            )
        )
