# Generated by Django 5.2.15 on 2026-06-28 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "documents",
            "0002_alter_authority_name_alter_documentdirection_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route_id",
                    models.CharField(
                        db_index=True,
                        max_length=10,
                        unique=True,
                        verbose_name="Route ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "document_procesc",
                    models.TextField(verbose_name="Документ / процесс из файла"),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название шаблона"
                    ),
                ),
                (
                    "required_fields",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Обязательное поле"
                    ),
                ),
                (
                    "required_attachments",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Обязательное вложение"
                    ),
                ),
                (
                    "submission_channel",
                    models.CharField(
                        choices=[
                            ("gosuslugi", "ЕПГУ"),
                            ("agency_account", "ЛК ведомства"),
                            ("edo", "ЭДО"),
                            ("office", "Канцелярия"),
                            ("post", "Почта с описью"),
                            ("email_duplicate", "E-mail дубль"),
                            ("manual", "Ручная подача"),
                        ],
                        default="manual",
                        max_length=30,
                        verbose_name="Канал подачи",
                    ),
                ),
                (
                    "source_url",
                    models.CharField(blank=True, verbose_name="Источник/форма"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Риск автоматизации",
                    ),
                ),
                (
                    "allow_auto_generation",
                    models.BooleanField(
                        default=True, verbose_name="Можно формировать автоматически"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routes",
                        to="documents.authority",
                        verbose_name="Основная инстанция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маршрут документа",
                "verbose_name_plural": "Маршруты документов",
                "ordering": ["route_id"],
            },
        ),
    ]
