# Generated by Django 5.2.15 on 2026-06-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentroute",
            old_name="document_procesc",
            new_name="document_process",
        ),
    ]
