# Generated by Django 5.2.15 on 2026-06-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_rename_document_procesc_documentroute_document_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentroute",
            name="source_url",
            field=models.CharField(blank=True, verbose_name="Источник / форма"),
        ),
    ]
