# Generated by Django 5.2.15 on 2026-06-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_alter_documentroute_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentroute",
            name="source_url",
            field=models.TextField(blank=True, verbose_name="Источник / форма"),
        ),
    ]
