# Generated by Django 5.2.15 on 2026-06-28 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documenttask_route"),
        ("submissions", "0004_alter_documentroute_source_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("ready", "Готов к подаче"),
                            ("sent", "Отправлено"),
                            ("registered", "Зарегистрировано"),
                            ("response_received", "Получен ответ"),
                            ("rejected", "Отказ / замечания"),
                            ("closed", "Закрыто"),
                            ("cancelled", "Отменено"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Статус подачи",
                    ),
                ),
                (
                    "outgoing_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Исходящий номер",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "agency_incoming_number",
                    models.CharField(
                        null=True, verbose_name="Вхоядщий номер ведомства"
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "proof_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="submission_proofs/",
                        verbose_name="Доказательство подачи",
                    ),
                ),
                ("comment", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_submission_packages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="submissions.documentroute",
                        verbose_name="Маршрут",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packages",
                        to="documents.documenttask",
                        verbose_name="Документ",
                    ),
                ),
            ],
        ),
    ]
