# Generated by Django 5.2.15 on 2026-06-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documenttask_route"),
        ("submissions", "0005_submissionpackage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionpackage",
            name="agency_incoming_number",
            field=models.CharField(null=True, verbose_name="Входящий номер ведомства"),
        ),
        migrations.AlterField(
            model_name="submissionpackage",
            name="comment",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="submissionpackage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="submissionpackage",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="submissions.documentroute",
                verbose_name="Маршрут",
            ),
        ),
        migrations.AlterField(
            model_name="submissionpackage",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="documents.documenttask",
                verbose_name="Документ",
            ),
        ),
        migrations.AlterField(
            model_name="submissionpackage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обнавлено"),
        ),
    ]
