# Generated by Django 5.2.15 on 2026-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0006_alter_submissionpackage_agency_incoming_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submissionpackage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Пакет отправки",
                "verbose_name_plural": "Пакеты отправки",
            },
        ),
        migrations.AlterField(
            model_name="submissionpackage",
            name="agency_incoming_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Входящий номер ведомства"
            ),
        ),
        migrations.AlterField(
            model_name="submissionpackage",
            name="outgoing_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Исходящий номер"
            ),
        ),
        migrations.AlterField(
            model_name="submissionpackage",
            name="registered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="submissionpackage",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отправки"
            ),
        ),
        migrations.AlterField(
            model_name="submissionpackage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
    ]
