# Generated by Django 5.2.15 on 2026-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0007_alter_submissionpackage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionpackage",
            name="field_values",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Значения полей формы"
            ),
        ),
    ]
