# Generated by Django 5.2.15 on 2026-07-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0008_submissionpackage_field_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionpackage",
            name="confirmed_attachments",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Подтвержденные вложения"
            ),
        ),
    ]
