# Generated by Django 5.2.15 on 2026-07-06 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0009_submissionpackage_confirmed_attachments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("approved", "Согласовано / принято"),
                            ("corrections_needed", "Замечания / доработка"),
                            ("rejected", "Отказ"),
                            ("info_request", "Запрос дополнительной информации"),
                        ],
                        max_length=30,
                        verbose_name="Тип ответа",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(verbose_name="Дата получения ответа"),
                ),
                (
                    "correction_due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок устранения замечаний"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "response_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="agency_responses/",
                        verbose_name="Файл ответа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agency_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто зафиксировал",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="submissions.submissionpackage",
                        verbose_name="Пакет отправки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ ведомства",
                "verbose_name_plural": "Ответы ведомств",
                "ordering": ["-received_at"],
            },
        ),
    ]
