# Generated by Django 5.2.15 on 2026-06-21 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Authority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название инстанции"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание инстанции"),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=50, verbose_name="Почта"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="Адрес"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Назначение")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание назначения"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MiningObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер лицензии"
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=150, verbose_name="Статус"),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "mining_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenses",
                        to="documents.miningobject",
                        verbose_name="Объект",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название документа"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "запланировано"),
                            ("in_progress", "в работе"),
                            ("send", "отправлено"),
                            ("received", "получено"),
                            ("done", "закрыто"),
                            ("overdue", "просрочено"),
                            ("cancelled", "отменено"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=False, verbose_name="Наличие документа"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="documents.authority",
                        verbose_name="Инстанция",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="documents.documentdirection",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный пользователь",
                    ),
                ),
                (
                    "license_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="documents.license",
                        verbose_name="Лицензия объекта",
                    ),
                ),
                (
                    "mining_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="documents.miningobject",
                        verbose_name="Объект",
                    ),
                ),
            ],
        ),
    ]
