# Generated by Django 5.2.15 on 2026-06-28 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="authority",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название инстанции"
            ),
        ),
        migrations.AlterField(
            model_name="documentdirection",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Назначение"
            ),
        ),
        migrations.AlterField(
            model_name="miningobject",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttask",
            index=models.Index(
                fields=["status", "deadline"], name="doc_task_status_deadline_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttask",
            index=models.Index(
                fields=["responsible", "deadline"], name="doc_task_resp_deadline_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttask",
            index=models.Index(
                fields=["mining_object", "direction"], name="doc_task_object_dir_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttask",
            constraint=models.UniqueConstraint(
                fields=("mining_object", "license_object", "direction", "title"),
                name="unique_document_task_plan_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="license",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("mining_object__isnull", False),
                    models.Q(("number", ""), _negated=True),
                ),
                fields=("mining_object", "number"),
                name="unique_license_per_object",
            ),
        ),
    ]
