# Generated by Django 5.2.15 on 2026-06-28 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0002_alter_authority_name_alter_documentdirection_name_and_more",
        ),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttask",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_tasks",
                to="submissions.documentroute",
                verbose_name="Маршрут автоматизации",
            ),
        ),
    ]
