# Generated by Django 5.2.15 on 2026-07-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documenttask_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="miningobject",
            name="cadastral_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Кадастровый номер участка"
            ),
        ),
        migrations.AddField(
            model_name="miningobject",
            name="municipality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Муниципальное образование"
            ),
        ),
        migrations.AddField(
            model_name="miningobject",
            name="nvos_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "I категория"),
                    ("II", "II категория"),
                    ("III", "III категория"),
                    ("IV", "IV категория"),
                ],
                max_length=5,
                verbose_name="Категория НВОС",
            ),
        ),
    ]
