# Generated by Django 5.2.15 on 2026-07-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_miningobject_cadastral_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authority",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="authority",
            name="block",
            field=models.CharField(
                blank=True,
                choices=[
                    ("subsoil", "Недра / лицензии / техпроекты"),
                    ("forest", "Лесной фонд"),
                    ("land", "Земля / муниципалитет"),
                    ("water", "Водопользование"),
                    ("ecology", "Экология / НВОС"),
                    ("sanitary", "Санитарно-эпидемиологический блок"),
                    ("emergency", "ГО и ЧС"),
                    ("other", "Прочее"),
                ],
                max_length=20,
                verbose_name="Блок",
            ),
        ),
        migrations.AddField(
            model_name="authority",
            name="preferred_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gosuslugi", "ЕПГУ"),
                    ("agency_account", "ЛК ведомства"),
                    ("edo", "ЭДО"),
                    ("office", "Канцелярия"),
                    ("post", "Почта с описью"),
                    ("email_duplicate", "E-mail дубль"),
                    ("manual", "Ручная подача"),
                ],
                max_length=30,
                verbose_name="Канал подачи по умолчанию",
            ),
        ),
    ]
