# Generated by Django 5.2.15 on 2026-07-06 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_authority_options_authority_block_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadlineReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold_days", models.IntegerField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="documents.documenttask",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "threshold_days"),
                        name="unique_task_deadline_reminder",
                    )
                ],
            },
        ),
    ]
