# Generated by Django 5.2.15 on 2026-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фотография"
            ),
        ),
    ]
