# Generated by Django 5.2.15 on 2026-06-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verifield",
            field=models.BooleanField(default=False),
        ),
    ]
