# Generated by Django 5.2.15 on 2026-06-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_email_verifield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="email_verifield",
            new_name="email_verified",
        ),
    ]
