# Generated by Django 5.2.15 on 2026-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_email_verifield_customuser_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Email подтвержден"),
        ),
    ]
