# Generated by Django 5.2.15 on 2026-06-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_manager_customuser_middle_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtitle",
            name="job_title",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Должность"
            ),
        ),
    ]
