# Generated by Django 5.2.15 on 2026-07-06 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_jobtitle_job_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("update", "Изменение"),
                            ("delete", "Удаление"),
                        ],
                        max_length=10,
                        verbose_name="Действие",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Модель")),
                (
                    "object_id",
                    models.CharField(max_length=50, verbose_name="ID объекта"),
                ),
                (
                    "object_repr",
                    models.CharField(max_length=200, verbose_name="Объект"),
                ),
                ("details", models.TextField(blank=True, verbose_name="Подробности")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись аудита",
                "verbose_name_plural": "Журнал аудита",
                "ordering": ["-created_at"],
            },
        ),
    ]
